security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    encoders:
        App\Entity\User: bcrypt
    access_control:
    - { path: ^/dashboard, roles: ROLE_ADMIN }
    providers:
        authenticate_admin:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            http_basic: ~
            logout:
                path: /logout
                target: /login
            form_login:
                        login_path: login
                        check_path: login
                        default_target_path: /dashboard
                        always_use_default_target_path: true
                        

            # activate different ways to authenticate

            # http_basic: ~
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # https://symfony.com/doc/current/security/form_login_setup.html
